ktor:
  application:
    modules:
      - com.aarokoinsaari.ApplicationKt.module
  deployment:
    port: 8080

redis:
  url: "redis://localhost:6379"

ingestion:
  archivePath: "enron_mail_20150507.tar.gz"
